# Generated by Django 3.2.6 on 2021-11-02 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='features',
            new_name='Feature',
        ),
    ]
